# Build & Deploy Puppet module & GitHub release when a SemVer tag is pushed
# ------------------------------------------------------------------------------
#
#             NOTICE: **This file is maintained with puppetsync**
#
# This file is updated automatically as part of a puppet module baseline.
#
# The next baseline sync will overwrite any local changes to this file!
#
# ==============================================================================
#
# This pipeline uses the following GitHub Action Secrets:
#
#   GitHub Secret variable    Type      Notes
#   ------------------------  --------  ----------------------------------------
#   PUPPETFORGE_API_TOKEN     Required
#
# ------------------------------------------------------------------------------
#
# NOTES:
#
# * The CHANGLOG text is altered to remove RPM-style date headers, which don't
#   render well as markdown on the GitHub release pages
---
name: 'Tag: Release to GitHub & Puppet Forge'

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

env:
  PUPPET_VERSION: '~> 6'

jobs:
  releng-checks:
    name: "RELENG checks"
    if: github.repository_owner == 'bolterrific'
    runs-on: ubuntu-18.04
    steps:
      - name: "Assert '${{ github.ref }}' is a tag"
        run: '[[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is not a tag: ${GITHUB_REF}"; exit 1 ; }'
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - run: bundle exec rake metadata_lint
      - run: bundle exec rake lint
      - run: |
          wget https://apt.puppet.com/puppet-tools-release-bionic.deb
          sudo dpkg -i puppet-tools-release-bionic.deb
          sudo apt-get update
          sudo apt-get install pdk
      - name: "Test that Puppet module can build"
        run: "pdk build --force"

  deploy-to-puppet-forge:
    name: Deploy PuppetForge Release
    needs: [ releng-checks ]
    if: github.repository_owner == 'bolterrific'
    runs-on: ubuntu-18.04
    env:
      PUPPETFORGE_API_TOKEN: ${{ secrets.PUPPETFORGE_API_TOKEN }}
      FORGE_USER_AGENT: GitHubActions-ForgeReleng-Workflow/0.4.0 (Purpose/forge-ops-for-${{ github.event.repository.name }})
      FORGE_API_URL: https://forgeapi.puppet.com/v3/releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Build Puppet module (PDK)
        run: bundle exec pdk build --force
      - name: Deploy to Puppet Forge
        run: |
          curl -X POST --silent --show-error --fail \
            --user-agent "$FORGE_USER_AGENT" \
            --header "Authorization: Bearer ${PUPPETFORGE_API_TOKEN}" \
            --form "file=@$(find $PWD/pkg -name ''*.tar.gz'')" \
            "$FORGE_API_URL"
